apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i4gt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-i4gt@sha256:a60e12d73eb09feebdb3dd468f3cc9e8557d6bb241767e9eb230916c6351ad9d
        name: my-nodejs
        resources: {}
status: {}
